# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrns0MVCmgF0-xBGbUOdsnI1JZxwFEYG
"""

import streamlit as st
import numpy as np
import pandas as pd
import shap
import pickle
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt
from streamlit_shap import st_shap

# ===== PAGE CONFIG =====
st.set_page_config(page_title="❤️ Heart Disease Risk Predictor", layout="wide")

# ===== HEADER =====
st.title("❤️ Heart Disease Risk Prediction Dashboard")
st.markdown("### Predict your heart disease risk using an AI-powered ANN with Explainable AI (SHAP)")
st.info("Fill in your health details in the sidebar and click **Predict** to view your risk, AI explanation, and personalized health tips.")

# ===== LOAD MODEL + SCALER =====
@st.cache_resource
def load_artifacts():
    model_path = r"heart_ann_model.h5"
    scaler_path = r"scaler.pkl"
    model = load_model(model_path)
    with open(scaler_path, "rb") as f:
        scaler = pickle.load(f)
    return model, scaler

model, scaler = load_artifacts()

# ===== SIDEBAR INPUT =====
st.sidebar.header("🧍 Patient Information")
st.sidebar.markdown("Please provide your details carefully for accurate predictions.")

age = st.sidebar.slider("Age (in years)", 20, 90, 45)
sex = st.sidebar.radio("Sex", ("Male", "Female"))
height = st.sidebar.number_input("Height (in cm)", 120, 220, 170)
weight = st.sidebar.number_input("Weight (in kg)", 30, 200, 70)
bmi = round(weight / ((height / 100) ** 2), 1)
st.sidebar.markdown(f"**Your BMI:** {bmi}")

cp = st.sidebar.selectbox("Chest Pain Type (CP)", ["0: Typical Angina", "1: Atypical Angina", "2: Non-anginal Pain", "3: Asymptomatic"])
trestbps = st.sidebar.slider("Resting Blood Pressure (mm Hg)", 80, 200, 120)
chol = st.sidebar.slider("Serum Cholesterol (mg/dl)", 100, 600, 200)
fbs = st.sidebar.radio("Fasting Blood Sugar > 120 mg/dl", ("No", "Yes"))
restecg = st.sidebar.selectbox("Resting ECG Results", ["0: Normal", "1: ST-T Abnormality", "2: Left Ventricular Hypertrophy"])
thalach = st.sidebar.slider("Maximum Heart Rate Achieved", 70, 210, 150)
exang = st.sidebar.radio("Exercise Induced Angina", ("No", "Yes"))
oldpeak = st.sidebar.slider("ST Depression (Oldpeak)", 0.0, 6.0, 1.0, 0.1)
slope = st.sidebar.selectbox("Slope of ST Segment", ["0: Upsloping", "1: Flat", "2: Downsloping"])
ca = st.sidebar.slider("Number of Major Vessels (0–3)", 0, 3, 0)
thal = st.sidebar.selectbox("Thalassemia", ["1: Normal", "2: Fixed Defect", "3: Reversible Defect"])

# Convert categorical text to numeric
sex = 1 if sex == "Male" else 0
fbs = 1 if fbs == "Yes" else 0
exang = 1 if exang == "Yes" else 0
cp = int(cp[0])
restecg = int(restecg[0])
slope = int(slope[0])
thal = int(thal[0])

# ===== LIFESTYLE RECOMMENDATIONS =====
def generate_recommendations(age, bmi, chol, trestbps, thalach, fbs, exang, risk_level):
    recs = []
    if bmi < 18.5: recs.append("🍚 Underweight — increase calorie intake with healthy proteins and carbs.")
    elif bmi > 25: recs.append("🥗 Overweight — reduce processed foods and exercise 30 min daily.")
    if chol > 240: recs.append("🍳 Reduce dietary cholesterol — prefer boiled or grilled food.")
    if trestbps > 140: recs.append("🧂 Lower salt intake and monitor blood pressure weekly.")
    if thalach < 100: recs.append("🏃 Increase aerobic activity like brisk walking or swimming.")
    if fbs == 1: recs.append("🍬 Control sugar intake and monitor fasting glucose levels regularly.")
    if exang == 1: recs.append("🚴 Avoid high-intensity workouts; opt for light cardio.")
    if age > 60 and risk_level != "Low": recs.append("🩺 Schedule regular ECGs and cardiac checkups every 6 months.")
    if not recs: recs.append("✅ Maintain your current lifestyle — your indicators are in a healthy range!")
    return recs

# ===== PREDICTION + SHAP =====
if st.sidebar.button("🔍 Predict"):
    # Scale input
    input_data = np.array([[age, sex, cp, trestbps, chol, fbs, restecg,
                            thalach, exang, oldpeak, slope, ca, thal]])
    scaled_data = scaler.transform(input_data)
    prediction = model.predict(scaled_data)[0][0]

    # --- Display Prediction ---
    st.subheader("📊 Prediction Results")
    if prediction < 0.4:
        st.success(f"✅ Low Risk ({prediction:.2f})")
        risk_level = "Low"
    elif prediction < 0.7:
        st.warning(f"⚠️ Moderate Risk ({prediction:.2f})")
        risk_level = "Medium"
    else:
        st.error(f"🚨 High Risk ({prediction:.2f})")
        risk_level = "High"

    # --- Lifestyle Recommendations ---
    st.markdown("### 💡 Personalized Lifestyle Recommendations")
    recs = generate_recommendations(age, bmi, chol, trestbps, thalach, fbs, exang, risk_level)
    for r in recs:
        st.write("- " + r)

    # --- SHAP Explainability ---
    st.markdown("### 🧠 Explainable AI (SHAP)")
    st.caption("These visualizations show which health factors most influenced your prediction.")
    background = np.random.normal(size=(50, scaled_data.shape[1]))

    def model_predict(data):
        return model.predict(data).flatten()

    explainer = shap.KernelExplainer(model_predict, background)
    shap_values = explainer.shap_values(scaled_data, nsamples=100)

    # Summary bar plot
    fig, ax = plt.subplots()
    shap.summary_plot(
        shap_values,
        scaled_data,
        feature_names=['age','sex','cp','trestbps','chol','fbs','restecg',
                       'thalach','exang','oldpeak','slope','ca','thal'],
        plot_type="bar",
        show=False
    )
    st.pyplot(fig)
    plt.close(fig)

    # Optional individual force plot
    try:
        shap.initjs()
        st.write("**Individual Explanation for Your Prediction**")
        force_html = shap.force_plot(
            explainer.expected_value,
            shap_values[0],
            scaled_data,
            feature_names=['age','sex','cp','trestbps','chol','fbs','restecg',
                           'thalach','exang','oldpeak','slope','ca','thal']
        )
        st.components.v1.html(shap.getjs(), height=300)
    except Exception as e:
        st.warning("Force plot unavailable: " + str(e))

# ===== ABOUT SECTION =====
with st.expander("ℹ️ About this App"):
    st.write("""
    This interactive dashboard uses a trained Artificial Neural Network (ANN)
    to predict the likelihood of heart disease. It includes:
    - 🧠 Explainable AI (SHAP) for transparency
    - 💡 Personalized lifestyle recommendations (including BMI)
    - 📊 Simple visualizations for non-technical users

    **Developed by:** Safwaan Siddiqui
    """)